/*
 * What the WebUI says, in English and Japanese. The page starts in the browser's language, and
 * the switch at the top right keeps the choice in localStorage. What the server says (errors,
 * findings) arrives as a key and arguments of src/shared/strings.ts and is put into words there,
 * in the same language. The model's own texts (names, purposes, Outcomes) are shown as written.
 */

import type { Language } from "../shared/types.ts";

const en = {
  "app.title": "ALPS Harness",
  "tab.network": "Network",
  "tab.dashboard": "Dashboard",
  "tab.instances": "Instances",
  "tabs.label": "Screens",
  "count.running": (a: { n: number }) => `Running ${a.n}`,
  "count.stale": (a: { n: number }) => `Stale evidence ${a.n}`,
  "language.switch": "日本語",
  "language.label": "Show the page in Japanese",
  "health.loading": "Connecting to the server…",
  "health.ok": (a: { version: string; pid: number; port: number; workspace: string }) =>
    `Server ${a.version} · pid ${a.pid} · port ${a.port} · ${a.workspace}`,
  "health.error": (a: { message: string }) => `Server unreachable: ${a.message}`,
  "events.retrying": "The connection to the server was lost; reconnecting…",
  "events.shutdown": "The harness server stopped. Start it again and open the URL that it prints.",
  "token.missing":
    "This page has no token. Open the URL that alps-harness serve printed (…/#token=…).",
  "error.title": "The request failed",
  retry: "Try again",
  "nav.menu": "Open the menu",
  "nav.close": "Close the menu",
  "workspace.label": "Workspace",
  "screen.network":
    "How the Processes and the Artifact types relate. The lines are not an order of execution.",
  "screen.dashboard":
    "What the runs and the judgments of a period add up to. The page counts; it judges nothing.",
  "screen.instances":
    "Each application of a Process to concrete inputs, with its runs and its evaluation.",
  "theme.label": "Theme",
  "theme.system": "System",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "display.title": "Display",
  "display.transparency": "Reduce transparency",
  "display.transparencyHint": "Surfaces become opaque.",
  "events.live": "Live",
  "events.connecting": "Connecting…",
  "events.reconnect": "Reconnect",
  "events.liveHint": "The page follows the records as they change.",
  "count.showRunning": "List the instances whose latest run is running",
  "count.showStale": "List the instances whose evidence is stale",
  loading: "Loading…",
  none: "—",

  "legend.output": "Output",
  "legend.input": "Input",
  "legend.control": "Control",
  "legend.running": "Running",
  "legend.stale": "Stale evidence",
  "legend.ringHint": "Click a Process or a type to see only what surrounds it.",
  "legend.focusHint":
    "Click the background to return to the whole ring, or another node to move the focus.",
  "legend.relations": "Artifact relationships",
  "legend.marks": "Marks",
  "legend.notOrder":
    "The lines show which Processes produce and read each Artifact type; they are not an order of execution.",
  "network.whole": "Whole model",
  "network.label": "The Processes and Artifact types of the model",
  "focus.producers": "Produce its inputs",
  "focus.inputs": "Inputs and controls",
  "focus.process": "Chosen Process",
  "focus.outputs": "Outputs",
  "focus.consumers": "Use its outputs",
  "focus.typeProducers": "Produce it",
  "focus.type": "Artifact type",
  "focus.typeConsumers": "Read it",
  "focus.typeSub": (a: { producers: number; consumers: number }) =>
    `produced by ${a.producers} · read by ${a.consumers}`,
  "focus.givenSub": (a: { consumers: number }) =>
    `given from outside the model · read by ${a.consumers}`,

  "panel.close": "Close",
  "panel.process": "Process",
  "panel.type": "Artifact type",
  "panel.run": "Run",
  "panel.instance": "Instance",
  "panel.model": "Model",
  "panel.label": "Details",
  "panel.open": "Show the model's overview",
  "panel.tabs": "Sections",
  "tab.overview": "Overview",
  "tab.skill": "SKILL.md",
  "overview.counts": (a: { processes: number; types: number }) =>
    `${a.processes} Processes · ${a.types} Artifact types`,
  "overview.workspace": "Workspace",
  "overview.agents": "Agents",
  "overview.available": "available",
  "overview.unavailable": (a: { reason: string }) => `unavailable: ${a.reason}`,
  "overview.wakes": "Wakes",
  "overview.noWakes":
    "No agent has been woken yet. The schedules in alps-harness.yaml, alps-harness wake, and the MCP tool wake wake one, which decides what to run.",
  "overview.hint":
    "Choose a Process or a type in the network, a number on the dashboard, or an instance to see it here.",
  "model.error": "The model cannot be read.",
  "model.files": "Files looked at",

  "process.purpose": "Purpose",
  "process.outcomes": "Outcomes",
  "process.inputs": "Inputs",
  "process.controls": "Controls",
  "process.outputs": "Outputs",
  "process.constraints": "Constraints",
  "process.enablers": "Enablers",
  "process.noSkill": "No SKILL.md is found for this Process.",
  "process.skillMissing": (a: { location: string }) =>
    `The declared Skill ${a.location} is not a readable SKILL.md.`,
  "process.truncated": "Only the beginning of the file is shown.",
  "process.instances": "Instances",
  "process.noInstances": "No instances yet.",
  "process.newInstance": "New instance",

  "type.kind": "Kind",
  "kind.information": "information",
  "kind.product": "product",
  "kind.service": "service",
  "kind.none": "not given",
  "type.locations": "Locations",
  "type.noLocation": "No location is configured (artifacts in alps-harness.yaml).",
  "type.producedBy": "Produced by",
  "type.readBy": "Read by",
  "type.nobody": "none",
  "type.artifacts": "Artifacts",
  "type.noArtifacts": "No Artifacts in its locations.",
  "type.truncated": "A location has more matches than one scan reads; the list is incomplete.",
  "type.madeBy": (a: { run: string }) => `made by ${a.run}`,
  "type.notMade": "no run made it",
  "type.items": (a: { n: number }) => `${a.n} items`,

  "status.running": "Running",
  "status.succeeded": "Succeeded",
  "status.failed": "Failed",
  "status.canceled": "Canceled",
  "status.interrupted": "Interrupted",
  "run.agent": "Agent",
  "run.instance": "Instance",
  "run.started": "Started",
  "run.ended": "Ended",
  "run.duration": "Duration",
  "run.usage": "Usage",
  "run.usageValue": (a: {
    cost: string;
    input: string;
    cached: string | null;
    output: string;
    turns: string | null;
  }) =>
    `${a.cost} · ${a.input} input${a.cached === null ? "" : ` (${a.cached} cached)`} · ${a.output} output tokens${a.turns === null ? "" : ` · ${a.turns} turns (tool round trips + 1)`}`,
  "run.report": "Report",
  "run.noReport": "No report.",
  "run.outputs": "Output changes",
  "run.noOutputs": "No output changes were found.",
  "run.created": "created",
  "run.modified": "modified",
  "run.sharedWith": (a: { runs: string }) =>
    `also an output of ${a.runs}, which ran at the same time: which run made it is not known`,
  "run.inputs": "Inputs it used",
  "run.missing": "missing",
  "run.log": "Log",
  "run.following": "Following the log…",
  "run.earlier": "Earlier events are left out.",
  "run.error": "Error",
  "run.cancel": "Cancel run",
  "run.canceling": "Canceling…",
  "run.wake": "Wake run",
  "run.startedRuns": "Runs it started",
  "run.noStartedRuns": "Its agent started no run.",
  "run.self": "performed by the calling session",

  "instance.inputs": "Inputs",
  "instance.outputs": "Outputs",
  "instance.decided": "decided by the agent",
  "instance.notYet": "not yet",
  "instance.criteria": "Criteria in this application",
  "instance.noCriteria":
    "No criteria were written: the Outcomes are read as the model states them.",
  "instance.checks": "Checks",
  "instance.notes": "Notes",
  "instance.runs": "Runs",
  "instance.noRuns": "Not run yet.",
  "instance.evaluation": "Evaluation",
  "instance.noEvaluation": "Not evaluated yet.",
  "instance.judgedRun": (a: { run: string; by: string; at: string }) =>
    `Judgments of ${a.run} by ${a.by}, ${a.at}`,
  "judge.user": "a person",
  "judge.self": (a: { id: string }) => `${a.id} (the performer's own judgment)`,
  "instance.evidence": "Evidence",
  "instance.limits": "Limits",
  "instance.note": "Note",
  "instance.staleTitle": "The evidence is stale",
  "instance.current":
    "The evidence is current: the inputs and the SKILL.md are as the judged run used them.",
  "stale.modified": (a: { path: string }) => `${a.path} changed`,
  "stale.created": (a: { path: string }) => `${a.path} appeared`,
  "stale.removed": (a: { path: string }) => `${a.path} was removed`,
  "stale.skill": (a: { path: string }) => `the SKILL.md changed (${a.path})`,
  "instance.agent": "Agent",
  "instance.start": "Start run",
  "instance.starting": "Starting…",
  "instance.noAgent": "No agent can be started.",
  "instance.unavailable": (a: { label: string }) => `${a.label} (unavailable)`,
  "instance.evaluate": "Evaluate",
  "instance.edit": "Edit criteria and notes",
  "instance.running": (a: { run: string }) => `Run ${a.run} is running.`,
  "instance.latest": "Latest run",
  "instance.judgments": "Judgments",
  "instance.logOf": (a: { run: string }) => `The log of run ${a.run}`,
  "instance.runVsOutcome":
    "A run that succeeded is not an achieved Outcome: only the judgments say whether an Outcome is achieved.",
  "run.openRecord": "Open the record of the run",
  "run.startFailed": "The run did not start.",
  "run.cancelFailed": "The run was not canceled.",

  "judgment.achieved": "Achieved",
  "judgment.not-achieved": "Not achieved",
  "judgment.unverified": "Unverified",

  "new.title": "New instance",
  "new.process": "Process",
  "new.choose": "Choose a Process",
  "new.inputs": "Inputs and controls",
  "new.outputs": "Outputs",
  "new.control": "control",
  "new.none": "No Artifacts of this type yet.",
  "new.path": "Another path in the workspace",
  "new.add": "Add",
  "new.remove": (a: { path: string }) => `Remove ${a.path}`,
  "new.agentDecides": "Let the agent decide",
  "new.criteria": "What each Outcome means in this application (optional)",
  "new.statement": "Criterion",
  "new.checks": "How to check it",
  "new.notes": "Notes (optional)",
  "new.create": "Create instance",
  "new.save": "Save criteria and notes",
  "new.cancel": "Cancel",
  "new.saving": "Saving…",
  "new.processRequired": "Choose a Process.",
  "new.pathEmpty": "Type a path first.",
  "new.pathPattern": "This is a pattern: name one file or directory.",
  "new.pathChosen": "This path is already chosen.",
  "new.pathNotType": (a: { type: string; patterns: string }) =>
    `Not in the locations of ${a.type} (${a.patterns}); it is kept as you wrote it.`,
  "new.failed": "The instance was not saved.",

  "evaluate.title": "Evaluate",
  "evaluate.of": (a: { run: string }) => `Judgments of run ${a.run}`,
  "evaluate.skip": "Not judged",
  "evaluate.evidence": "Evidence (required)",
  "evaluate.limits": "Limits (optional)",
  "evaluate.note": "Note (Markdown, optional)",
  "evaluate.save": "Record the evaluation",
  "evaluate.needOne": "Judge at least one Outcome, each with its evidence.",
  "evaluate.hint":
    "Only the three values are counted. Write what you read or tried to judge: a run that ended or an output that exists is not an achievement.",
  "evaluate.evidenceRequired": "Write the evidence of this judgment.",
  "evaluate.failed": "The evaluation was not recorded.",

  "filter.period": "Period",
  "period.7d": "7 days",
  "period.30d": "30 days",
  "period.90d": "90 days",
  "period.all": "All time",
  "filter.granularity": "By",
  "granularity.day": "Day",
  "granularity.week": "Week",
  "filter.process": "Process",
  "filter.agent": "Agent",
  "filter.all": "All",
  "metric.achievement": "Outcome achievement",
  "metric.unverified": "Unverified",
  "metric.stale": "Stale evaluations",
  "metric.runSuccess": "Runs succeeded",
  "metric.duration": "Median duration",
  "metric.cost": "Usage and cost",
  "metric.judged": (a: { n: number; d: number }) => `${a.n} of ${a.d} judged Outcomes`,
  "metric.awaiting": (a: { n: number }) => `${a.n} of the instances await a judgment`,
  "metric.staleSub": "inputs or SKILL.md changed after the judgment",
  "metric.ended": (a: { n: number; d: number }) => `${a.n} of ${a.d} ended runs`,
  "metric.p90": (a: { p90: string }) => `p90 ${a.p90}`,
  "metric.perAchieved": (a: { cost: string }) => `${a.cost} per achieved Outcome`,
  "metric.tokens": (a: { input: string; cached: string | null; output: string }) =>
    `${a.input} in${a.cached === null ? "" : ` (${a.cached} cached)`} · ${a.output} out tokens`,
  "metric.noUsage": "The agents reported no usage.",
  "unit.items": "",
  "trend.runs": "Runs and results",
  "trend.judgments": "Judgments and achievement rate",
  "trend.cost": "Cost by agent",
  "trend.duration": "Duration: median, whisker to p90",
  "trend.noData": "Nothing in this period.",
  "dashboard.error": "The statistics cannot be read.",
  "metric.now": "now",
  "chart.keys": "The arrow keys choose a period; Enter lists what it counts.",
  "breakdown.hint": "A row lists what it counts.",
  "findings.title": "Findings",
  "findings.sub":
    "What the assessment finds: problems of the description or the configuration, and what is unverified.",
  "findings.none": "No findings.",
  "findings.more": (a: { n: number }) => `Show all ${a.n}`,
  "findings.less": "Show fewer",
  "findings.error": "The findings cannot be read.",
  "findingKind.description": "Description",
  "findingKind.configuration": "Configuration",
  "findingKind.unverified": "Unverified",
  "trend.rate": "achievement rate",
  "breakdown.title": "Breakdown",
  "breakdown.process": "By Process",
  "breakdown.agent": "By agent",
  "breakdown.outcome": "By Outcome",
  "breakdown.judge": "By judge",
  "col.process": "Process",
  "col.instances": "Instances",
  "col.runs": "Runs",
  "col.runSuccess": "Succeeded",
  "col.median": "Median",
  "col.achievement": "Achieved",
  "col.unverified": "Unverified",
  "col.cost": "Cost",
  "col.agent": "Agent",
  "col.perAchieved": "Cost per achieved",
  "col.runsPerInstance": "Runs per instance",
  "col.outcome": "Outcome",
  "col.counts": "Achieved · not achieved · unverified",
  "col.judge": "Judge",
  "col.judgments": "Judgments",
  "col.firstInput": "Input",
  "col.latestRun": "Latest run",
  "col.evidence": "Evidence",
  "col.updated": "Updated",
  "judgeKind.user": "People",
  "judgeKind.agent": "Agents",
  "judgeKind.self": "The performer's own",
  "outcome.never": "judged, never achieved",
  "outcome.mostlyUnverified": "mostly unverified",
  "outcome.unjudged": "never judged",
  "members.instances": "Instances",
  "members.runs": "Runs",
  "members.none": "Nothing is counted here.",
  "members.since": (a: { from: string }) => `Since ${a.from}`,
  "members.allTime": "All time",
  "members.now": "As it is now, whatever the period",
  "members.bucket": (a: { from: string }) => `From ${a.from}`,

  "instances.status": "Latest run",
  "instances.judgment": "Judgment",
  "instances.path": "Path contains",
  "instances.any": "Any",
  "instances.notRun": "Not run",
  "instances.judged": "Judged",
  "instances.unjudged": "Not judged",
  "instances.staleOnly": "Stale evidence",
  "instances.stale": "stale",
  "instances.currentEvidence": "current",
  "instances.none": "No instances match.",
  "instances.empty": "No instances yet. Create one for a Process.",
  "instances.count": (a: { n: number; total: number }) => `${a.n} of ${a.total}`,
  "instances.clear": "Clear the filters",
  "instances.pathPlaceholder": "Part of a path",
} satisfies Record<string, string | ((args: never) => string)>;

export type UiKey = keyof typeof en;

const ja: { [K in UiKey]: (typeof en)[K] } = {
  "app.title": "ALPS Harness",
  "tab.network": "ネットワーク",
  "tab.dashboard": "ダッシュボード",
  "tab.instances": "インスタンス",
  "tabs.label": "画面",
  "count.running": (a) => `実行中 ${a.n}`,
  "count.stale": (a) => `根拠が古い ${a.n}`,
  "language.switch": "English",
  "language.label": "英語で表示する",
  "health.loading": "サーバーに接続している…",
  "health.ok": (a) => `サーバー ${a.version} · pid ${a.pid} · ポート ${a.port} · ${a.workspace}`,
  "health.error": (a) => `サーバーに接続できない: ${a.message}`,
  "events.retrying": "サーバーとの接続が切れた。再接続している…",
  "events.shutdown": "ハーネスサーバーが停止した。起動し直し、印字された URL を開くこと。",
  "token.missing":
    "このページには合い言葉がない。alps-harness serve が印字した URL（…/#token=…）を開くこと。",
  "error.title": "要求は失敗した",
  retry: "もう一度試す",
  "nav.menu": "メニューを開く",
  "nav.close": "メニューを閉じる",
  "workspace.label": "ワークスペース",
  "screen.network": "プロセスとアーティファクトの型の関係。線は実行の順序を表さない。",
  "screen.dashboard": "期間内の実行と判断の集計。画面は数えるだけで、判断はしない。",
  "screen.instances": "プロセスを具体的な入力に適用した一つひとつと、その実行と評価。",
  "theme.label": "テーマ",
  "theme.system": "システム",
  "theme.light": "ライト",
  "theme.dark": "ダーク",
  "display.title": "表示",
  "display.transparency": "透明度を下げる",
  "display.transparencyHint": "面が不透明になる。",
  "events.live": "ライブ",
  "events.connecting": "接続している…",
  "events.reconnect": "再接続",
  "events.liveHint": "記録が変わると、画面もそのとおりに変わる。",
  "count.showRunning": "最新の実行が実行中のインスタンスを一覧する",
  "count.showStale": "根拠が古いインスタンスを一覧する",
  loading: "読み込み中…",
  none: "—",

  "legend.output": "出力",
  "legend.input": "入力",
  "legend.control": "統制事項",
  "legend.running": "実行中",
  "legend.stale": "根拠が古い",
  "legend.ringHint": "プロセスか型をクリックすると、その前後だけの焦点図になる。",
  "legend.focusHint": "空白をクリックで全体へ戻る。ほかのノードをクリックすると焦点が移る。",
  "legend.relations": "アーティファクトの関係",
  "legend.marks": "印",
  "legend.notOrder":
    "線は、各アーティファクトの型をどのプロセスが作り、どのプロセスが読むかを示す。実行の順序ではない。",
  "network.whole": "モデル全体",
  "network.label": "モデルのプロセスとアーティファクトの型",
  "focus.producers": "入力を作る",
  "focus.inputs": "入力・統制事項",
  "focus.process": "選んだプロセス",
  "focus.outputs": "出力",
  "focus.consumers": "出力を使う",
  "focus.typeProducers": "作るプロセス",
  "focus.type": "型",
  "focus.typeConsumers": "使うプロセス",
  "focus.typeSub": (a) => `作る ${a.producers} · 使う ${a.consumers}`,
  "focus.givenSub": (a) => `外から与えられる型 · 使う ${a.consumers}`,

  "panel.close": "閉じる",
  "panel.process": "プロセス",
  "panel.type": "アーティファクトの型",
  "panel.run": "実行",
  "panel.instance": "インスタンス",
  "panel.model": "モデル",
  "panel.label": "詳細",
  "panel.open": "モデルの概要を表示",
  "panel.tabs": "区分",
  "tab.overview": "概要",
  "tab.skill": "SKILL.md",
  "overview.counts": (a) => `プロセス ${a.processes} · アーティファクトの型 ${a.types}`,
  "overview.workspace": "ワークスペース",
  "overview.agents": "エージェント",
  "overview.available": "使える",
  "overview.unavailable": (a) => `使えない: ${a.reason}`,
  "overview.wakes": "目覚めの記録",
  "overview.noWakes":
    "まだ目覚めたエージェントはない。alps-harness.yaml の schedules、alps-harness wake、MCP の wake がエージェントを起こし、エージェントが何を走らせるかを判断する。",
  "overview.hint":
    "ネットワークのプロセスや型、ダッシュボードの数字、インスタンスを選ぶと、ここに詳細が出る。",
  "model.error": "モデルを読めない。",
  "model.files": "見たファイル",

  "process.purpose": "目的",
  "process.outcomes": "成果",
  "process.inputs": "入力",
  "process.controls": "統制事項",
  "process.outputs": "出力",
  "process.constraints": "制約",
  "process.enablers": "実行支援要素",
  "process.noSkill": "このプロセスの SKILL.md は見つからない。",
  "process.skillMissing": (a) => `指定されたスキル ${a.location} は読める SKILL.md ではない。`,
  "process.truncated": "ファイルの先頭だけを表示している。",
  "process.instances": "インスタンス",
  "process.noInstances": "インスタンスはまだない。",
  "process.newInstance": "インスタンス化",

  "type.kind": "種類",
  "kind.information": "情報",
  "kind.product": "製品",
  "kind.service": "サービス",
  "kind.none": "指定なし",
  "type.locations": "置き場所",
  "type.noLocation": "置き場所の設定がない（alps-harness.yaml の artifacts）。",
  "type.producedBy": "作るプロセス",
  "type.readBy": "読むプロセス",
  "type.nobody": "なし",
  "type.artifacts": "実体",
  "type.noArtifacts": "置き場所に実体はない。",
  "type.truncated": "一回の走査で読める数を超えた置き場所があり、一覧は不完全である。",
  "type.madeBy": (a) => `${a.run} が作成`,
  "type.notMade": "実行の記録なし",
  "type.items": (a) => `${a.n} 項目`,

  "status.running": "実行中",
  "status.succeeded": "正常終了",
  "status.failed": "異常終了",
  "status.canceled": "中止",
  "status.interrupted": "中断",
  "run.agent": "エージェント",
  "run.instance": "インスタンス",
  "run.started": "開始",
  "run.ended": "終了",
  "run.duration": "所要時間",
  "run.usage": "使用量",
  "run.usageValue": (a) =>
    `${a.cost} · 入力 ${a.input}${a.cached === null ? "" : `（キャッシュ ${a.cached}）`} · 出力 ${a.output} トークン${a.turns === null ? "" : ` · ターン ${a.turns}（ツールの往復＋1）`}`,
  "run.report": "報告",
  "run.noReport": "報告はない。",
  "run.outputs": "出力の変化",
  "run.noOutputs": "出力の変化は見つからなかった。",
  "run.created": "作成",
  "run.modified": "更新",
  "run.sharedWith": (a) => `同時に動いた ${a.runs} の出力でもあり、どの実行が作ったかは分からない`,
  "run.inputs": "使った入力",
  "run.missing": "なかった",
  "run.log": "ログ",
  "run.following": "ログを追っている…",
  "run.earlier": "それより前のイベントは省いた。",
  "run.error": "エラー",
  "run.cancel": "実行を中止",
  "run.canceling": "中止している…",
  "run.wake": "目覚めの実行",
  "run.startedRuns": "起動した実行",
  "run.noStartedRuns": "起動した実行はない。",
  "run.self": "呼び出し元のセッションが実行",

  "instance.inputs": "入力",
  "instance.outputs": "出力",
  "instance.decided": "エージェントが決める",
  "instance.notYet": "まだない",
  "instance.criteria": "この適用での基準",
  "instance.noCriteria": "基準は書かれていない。成果はモデルの記述のとおりに読む。",
  "instance.checks": "確かめ方",
  "instance.notes": "注記",
  "instance.runs": "実行",
  "instance.noRuns": "まだ実行していない。",
  "instance.evaluation": "評価",
  "instance.noEvaluation": "まだ評価していない。",
  "instance.judgedRun": (a) => `${a.run} についての判断（${a.by}、${a.at}）`,
  "judge.user": "人",
  "judge.self": (a) => `${a.id}（実行者自身の判断）`,
  "instance.evidence": "根拠",
  "instance.limits": "限界",
  "instance.note": "注記",
  "instance.staleTitle": "根拠が古い",
  "instance.current": "根拠は最新である。入力と SKILL.md は判断した実行が使ったときのままである。",
  "stale.modified": (a) => `${a.path} が変わった`,
  "stale.created": (a) => `${a.path} が現れた`,
  "stale.removed": (a) => `${a.path} が消えた`,
  "stale.skill": (a) => `SKILL.md が変わった（${a.path}）`,
  "instance.agent": "エージェント",
  "instance.start": "実行する",
  "instance.starting": "開始している…",
  "instance.noAgent": "起動できるエージェントがない。",
  "instance.unavailable": (a) => `${a.label}（使えない）`,
  "instance.evaluate": "評価する",
  "instance.edit": "基準と注記を直す",
  "instance.running": (a) => `実行 ${a.run} が実行中である。`,
  "instance.latest": "最新の実行",
  "instance.judgments": "判断",
  "instance.logOf": (a) => `実行 ${a.run} のログ`,
  "instance.runVsOutcome":
    "実行の正常終了は成果の達成ではない。成果が達成されたかどうかは判断だけが示す。",
  "run.openRecord": "実行の記録を開く",
  "run.startFailed": "実行は始まらなかった。",
  "run.cancelFailed": "実行は中止されなかった。",

  "judgment.achieved": "達成",
  "judgment.not-achieved": "未達成",
  "judgment.unverified": "未確認",

  "new.title": "インスタンス化",
  "new.process": "プロセス",
  "new.choose": "プロセスを選ぶ",
  "new.inputs": "入力と統制事項",
  "new.outputs": "出力",
  "new.control": "統制事項",
  "new.none": "この型の実体はまだない。",
  "new.path": "ワークスペース内のほかのパス",
  "new.add": "追加",
  "new.remove": (a) => `${a.path} を外す`,
  "new.agentDecides": "エージェントに任せる",
  "new.criteria": "この適用での各成果の意味（任意）",
  "new.statement": "基準",
  "new.checks": "確かめ方",
  "new.notes": "注記（任意）",
  "new.create": "インスタンスを作る",
  "new.save": "基準と注記を保存",
  "new.cancel": "やめる",
  "new.saving": "保存している…",
  "new.processRequired": "プロセスを選ぶこと。",
  "new.pathEmpty": "先にパスを入力すること。",
  "new.pathPattern": "これはパターンである。ファイルかディレクトリを一つ指すこと。",
  "new.pathChosen": "このパスは選択済みである。",
  "new.pathNotType": (a) => `${a.type} の置き場所（${a.patterns}）に合わない。書いたとおりに残す。`,
  "new.failed": "インスタンスは保存されなかった。",

  "evaluate.title": "評価",
  "evaluate.of": (a) => `実行 ${a.run} についての判断`,
  "evaluate.skip": "判断しない",
  "evaluate.evidence": "根拠（必須）",
  "evaluate.limits": "限界（任意）",
  "evaluate.note": "注記（Markdown、任意）",
  "evaluate.save": "評価を記録",
  "evaluate.needOne": "少なくとも一つの成果を、根拠を添えて判断すること。",
  "evaluate.hint":
    "数えるのは三値だけである。判断のために読んだものや試したことを書く。実行が終わったことや出力があることは達成ではない。",
  "evaluate.evidenceRequired": "この判断の根拠を書くこと。",
  "evaluate.failed": "評価は記録されなかった。",

  "filter.period": "期間",
  "period.7d": "7 日",
  "period.30d": "30 日",
  "period.90d": "90 日",
  "period.all": "全期間",
  "filter.granularity": "粒度",
  "granularity.day": "日",
  "granularity.week": "週",
  "filter.process": "プロセス",
  "filter.agent": "エージェント",
  "filter.all": "すべて",
  "metric.achievement": "成果の達成率",
  "metric.unverified": "未確認率",
  "metric.stale": "根拠が古い評価",
  "metric.runSuccess": "実行の正常終了率",
  "metric.duration": "所要時間の中央値",
  "metric.cost": "使用量と費用",
  "metric.judged": (a) => `判断 ${a.d} 件のうち ${a.n}`,
  "metric.awaiting": (a) => `判断待ちのインスタンス ${a.n} 件`,
  "metric.staleSub": "判断の後に入力か SKILL.md が変わった",
  "metric.ended": (a) => `終わった実行 ${a.d} 件のうち ${a.n}`,
  "metric.p90": (a) => `p90 ${a.p90}`,
  "metric.perAchieved": (a) => `達成 1 件あたり ${a.cost}`,
  "metric.tokens": (a) =>
    `トークン 入力 ${a.input}${a.cached === null ? "" : `（キャッシュ ${a.cached}）`} · 出力 ${a.output}`,
  "metric.noUsage": "エージェントが使用量を報告していない。",
  "unit.items": "件",
  "trend.runs": "実行数と結果",
  "trend.judgments": "判断と達成率",
  "trend.cost": "エージェント別の費用",
  "trend.duration": "所要時間：中央値と p90 までの髭",
  "trend.noData": "この期間には何もない。",
  "dashboard.error": "統計を読めない。",
  "metric.now": "現在",
  "chart.keys": "矢印キーで期間を選び、Enter でその期間に数えたものを一覧する。",
  "breakdown.hint": "行を選ぶと、数えたものを一覧する。",
  "findings.title": "所見",
  "findings.sub": "点検で見つかったもの：記述や構成の問題と、未確認のもの。",
  "findings.none": "所見はない。",
  "findings.more": (a) => `${a.n} 件すべて表示`,
  "findings.less": "表示を減らす",
  "findings.error": "所見を読めない。",
  "findingKind.description": "記述",
  "findingKind.configuration": "構成",
  "findingKind.unverified": "未確認",
  "trend.rate": "達成率",
  "breakdown.title": "内訳",
  "breakdown.process": "プロセス別",
  "breakdown.agent": "エージェント別",
  "breakdown.outcome": "成果別",
  "breakdown.judge": "判断者別",
  "col.process": "プロセス",
  "col.instances": "インスタンス",
  "col.runs": "実行",
  "col.runSuccess": "正常終了率",
  "col.median": "中央値",
  "col.achievement": "達成率",
  "col.unverified": "未確認率",
  "col.cost": "費用",
  "col.agent": "エージェント",
  "col.perAchieved": "達成あたりの費用",
  "col.runsPerInstance": "インスタンスあたりの実行",
  "col.outcome": "成果",
  "col.counts": "達成・未達成・未確認",
  "col.judge": "判断者",
  "col.judgments": "判断",
  "col.firstInput": "入力",
  "col.latestRun": "最新の実行",
  "col.evidence": "根拠",
  "col.updated": "更新",
  "judgeKind.user": "人",
  "judgeKind.agent": "エージェント",
  "judgeKind.self": "実行者自身",
  "outcome.never": "判断されたが一度も達成されていない",
  "outcome.mostlyUnverified": "未確認が過半",
  "outcome.unjudged": "判断されていない",
  "members.instances": "インスタンス",
  "members.runs": "実行",
  "members.none": "数えたものはない。",
  "members.since": (a) => `${a.from} 以降`,
  "members.allTime": "全期間",
  "members.now": "期間に関わらず今の状態",
  "members.bucket": (a) => `${a.from} から`,

  "instances.status": "最新の実行",
  "instances.judgment": "判断",
  "instances.path": "パスの一部",
  "instances.any": "すべて",
  "instances.notRun": "未実行",
  "instances.judged": "判断あり",
  "instances.unjudged": "判断なし",
  "instances.staleOnly": "根拠が古い",
  "instances.stale": "古い",
  "instances.currentEvidence": "最新",
  "instances.none": "該当するインスタンスはない。",
  "instances.empty": "インスタンスはまだない。プロセスを選んでインスタンス化すること。",
  "instances.count": (a) => `${a.total} 件中 ${a.n} 件`,
  "instances.clear": "絞り込みを解除",
  "instances.pathPlaceholder": "パスの一部",
};

const CATALOG: Record<Language, { [K in UiKey]: (typeof en)[K] }> = { en, ja };

/** The arguments of a text: none for a plain string. */
export type UiArgs<K extends UiKey> = (typeof en)[K] extends (args: infer A) => string ? [A] : [];

/** A text of the WebUI in a language. */
export function text<K extends UiKey>(language: Language, key: K, ...args: UiArgs<K>): string {
  const entry = CATALOG[language][key] as string | ((args: unknown) => string);
  return typeof entry === "string" ? entry : entry(args[0]);
}

export type Translate = <K extends UiKey>(key: K, ...args: UiArgs<K>) => string;

export const translator =
  (language: Language): Translate =>
  (key, ...args) =>
    text(language, key, ...args);

/** The browser's language, if the WebUI speaks it; English otherwise. */
export function browserLanguage(languages: readonly string[]): Language {
  for (const tag of languages) {
    const primary = tag.toLowerCase().split("-")[0];
    if (primary === "ja") return "ja";
    if (primary === "en") return "en";
  }
  return "en";
}
