/*
 * What the WebUI says, in English and Japanese. The page starts in the browser's language, and
 * the switch at the top right keeps the choice in localStorage. What the server says (errors,
 * findings) arrives as a key and arguments of src/shared/strings.ts and is put into words there,
 * in the same language. The model's own texts (names, purposes, Outcomes) are shown as written.
 */

import type { Language } from "../shared/types.ts";

const en = {
  "agent.model": "Model",
  "agent.effort": "Effort",
  "agent.default": "Agent default",
  "agent.loading": "Loading models…",
  "agent.noEffort": "Not supported",
  "agent.loadFailed": "Could not load models. Agent defaults are still available.",
  "agent.liveChoices": "Available in the installed CLI",
  "agent.refresh": "Refresh",
  "app.title": "ALPS Harness",
  // The sidebar's heading: the name, then the product in small capitals; together, the title.
  "brand.name": "ALPS",
  "brand.product": "Harness",
  "tab.network": "Network",
  "tab.dashboard": "Analysis",
  "tab.instances": "Board",
  "tabs.label": "Screens",
  "count.running": (a: { n: number }) => `Running ${a.n}`,
  "count.stale": (a: { n: number }) => `Stale evidence ${a.n}`,
  "language.switch": "日本語",
  "language.label": "Show the page in Japanese",
  "health.loading": "Connecting to the server…",
  "health.ok": (a: { version: string; pid: number; port: number }) =>
    `Server ${a.version} · pid ${a.pid} · port ${a.port}`,
  "health.error": (a: { message: string }) => `Server unreachable: ${a.message}`,
  "events.retrying": "The connection to the server was lost; reconnecting…",
  "events.shutdown": "The harness server stopped. Start it again and open the URL that it prints.",
  "token.missing":
    "This page has no token. Open the URL that alps-harness serve printed (…/#token=…).",
  "error.title": "The request failed",
  retry: "Try again",
  "nav.menu": "Open the menu",
  "nav.close": "Close the menu",
  "filter.allProcesses": "All processes",
  "filter.allAgents": "All agents",
  "theme.label": "Theme",
  "theme.system": "System",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "display.transparency": "Reduce transparency",
  "events.live": "Live",
  "events.connecting": "Connecting…",
  "events.offline": "Offline",
  "events.reconnect": "Reconnect",
  "count.showRunning": "List the instances whose latest run is running",
  "count.showStale": "List the instances whose evidence is stale",
  loading: "Loading…",
  none: "—",

  "legend.show": "Legend",
  "legend.hide": "Hide the legend",
  "legend.lines": "Input or output",
  "legend.control": "Control",
  "legend.running": "Running",
  "legend.stale": "Stale evidence",
  "legend.relation": "A line is a relation, not an order of execution.",
  "legend.use":
    "Click a node to show only what is around it, and the background to show everything.",
  "network.whole": "Whole model",
  "network.label": "The Processes and Artifact types of the model",
  "focus.producers": "Produce its inputs",
  "focus.inputs": "Inputs and controls",
  "focus.process": "Chosen Process",
  "focus.outputs": "Outputs",
  "focus.consumers": "Use its outputs",
  "focus.typeProducers": "Produce it",
  "focus.type": "Artifact type",
  "focus.typeConsumers": "Read it",
  "focus.given": "given from outside the model",

  "panel.close": "Close",
  "panel.process": "Process",
  "panel.type": "Artifact type",
  "panel.run": "Run",
  "panel.instance": "Instance",
  "panel.model": "Model",
  "panel.label": "Details",
  "panel.open": "Show the model's overview",
  "panel.tabs": "Sections",
  "tab.overview": "Overview",
  "tab.skill": "SKILL.md",
  "overview.processes": "Processes",
  "overview.types": "Artifact types",
  "overview.workspace": "Workspace",
  "overview.agents": "Agents",
  "overview.available": "available",
  "overview.unavailable": (a: { reason: string }) => `unavailable: ${a.reason}`,
  "overview.wakes": "Wakes",
  "overview.noWakes": "No wakes yet.",
  "model.error": "The model cannot be read.",
  "model.files": "Files looked at",

  "process.outcomes": "Outcomes",
  "process.inputs": "Inputs",
  "process.controls": "Controls",
  "process.outputs": "Outputs",
  "process.constraints": "Constraints",
  "process.enablers": "Enablers",
  "process.noSkill": "No SKILL.md is found for this Process.",
  "process.skillMissing": (a: { location: string }) =>
    `The declared Skill ${a.location} is not a readable SKILL.md.`,
  "process.truncated": "Only the beginning of the file is shown.",
  "process.instances": "Instances",
  "process.noInstances": "No instances yet.",
  "process.request": "Request with this Process",

  "type.kind": "Kind",
  "kind.information": "information",
  "kind.product": "product",
  "kind.service": "service",
  "kind.none": "not given",
  "type.locations": "Locations",
  "type.noLocation": "No location is configured (artifacts in alps-harness.yaml).",
  "type.producedBy": "Produced by",
  "type.readBy": "Read by",
  "type.nobody": "none",
  "type.artifacts": "Artifacts",
  "type.noArtifacts": "No Artifacts in its locations.",
  "type.truncated": "A location has more matches than one scan reads; the list is incomplete.",
  "type.notMade": "no run made it",
  "type.items": (a: { n: number }) => `${a.n} items`,

  "status.running": "Running",
  "status.succeeded": "Succeeded",
  "status.failed": "Failed",
  "status.canceled": "Canceled",
  "status.interrupted": "Interrupted",
  "run.agent": "Agent",
  "run.instance": "Instance",
  "run.started": "Started",
  "run.ended": "Ended",
  "run.duration": "Duration",
  "run.usage": "Usage",
  "run.usageValue": (a: {
    cost: string;
    input: string;
    cached: string | null;
    output: string;
    turns: string | null;
  }) =>
    `${a.cost} · ${a.input} input${a.cached === null ? "" : ` (${a.cached} cached)`} · ${a.output} output tokens${a.turns === null ? "" : ` · ${a.turns} turns`}`,
  "run.turns": "Turns are the tool round trips plus one.",
  "run.report": "Report",
  "run.planReport": "Report: what it planned and why",
  "run.noReport": "No report.",
  "run.request": "Request",
  "run.noRequestText": "The request had no text.",
  "run.processes": "Processes asked for",
  "run.attachments": "Attachments",
  "run.madeInstances": "Instances it made",
  "run.noMadeInstances": "None yet.",
  "run.outputs": "Output changes",
  "run.noOutputs": "No output changes were found.",
  "run.created": "created",
  "run.modified": "modified",
  "run.sharedWith": (a: { runs: string }) =>
    `also an output of ${a.runs}, which ran at the same time: which run made it is not known`,
  "run.inputs": "Inputs it used",
  "run.missing": "missing",
  "run.log": "Log",
  "run.following": "Following the log…",
  "run.earlier": "Earlier events are left out.",
  "run.error": "Error",
  "run.cancel": "Cancel run",
  "run.canceling": "Canceling…",
  "run.wake": "Wake run",
  "run.wakeTitle": "Wake",
  "run.startedRuns": "Runs it started",
  "run.noStartedRuns": "Its agent started no run.",
  "run.self": "performed by the calling session",
  "run.assess": "Assessment run",
  "run.assessTitle": "Assessment",
  "run.scope": "Scope",

  "instance.inputs": "Inputs",
  "instance.outputs": "Outputs",
  "instance.decided": "decided by the agent",
  "instance.notYet": "not yet",
  "instance.criteria": "Criteria",
  "instance.asStated": "No criterion is written: the Outcome is read as the model states it.",
  "instance.checks": "Checks",
  "instance.notes": "Notes",
  "instance.runs": "Runs",
  "instance.noRuns": "Not run yet.",
  "instance.evaluation": "Evaluation",
  "instance.noEvaluation": "Not evaluated yet.",
  "instance.judgedRun": (a: { run: string; by: string; at: string }) =>
    `Judgments of ${a.run} by ${a.by}, ${a.at}`,
  "judge.user": "a person",
  "judge.self": (a: { id: string }) => `${a.id} (the performer's own judgment)`,
  "instance.evidence": "Evidence",
  "instance.limits": "Limits",
  "instance.note": "Note",
  "instance.staleTitle": "The evidence is stale",
  "instance.current": "The evidence is current",
  "instance.currentHint": "The inputs and the SKILL.md are as the judged run used them.",
  "stale.modified": (a: { path: string }) => `${a.path} changed`,
  "stale.created": (a: { path: string }) => `${a.path} appeared`,
  "stale.removed": (a: { path: string }) => `${a.path} was removed`,
  "stale.skill": (a: { path: string }) => `the SKILL.md changed (${a.path})`,
  "stale.definition": "the Process description or application criteria changed",
  "instance.agent": "Agent",
  "instance.start": "Start run",
  "instance.starting": "Starting…",
  "instance.noAgent": "No agent can be started.",
  "instance.unavailable": (a: { label: string }) => `${a.label} (unavailable)`,
  "instance.evaluate": "Evaluate",
  "instance.edit": "Edit criteria and notes",
  "instance.latest": "Latest run",
  "instance.judgments": "Judgments",
  "instance.createdBy": "Made by the wake",
  "instance.earlier": "Earlier evaluations",
  "run.startFailed": "The run did not start.",
  "run.cancelFailed": "The run was not canceled.",

  "judgment.achieved": "Achieved",
  "judgment.not-achieved": "Not achieved",
  "judgment.unverified": "Unverified",

  "new.criteria": "What each Outcome means in this application (optional)",
  "new.statement": "Criterion",
  "new.checks": "How to check it",
  "new.notes": "Notes (optional)",
  "new.save": "Save criteria and notes",
  "new.cancel": "Cancel",
  "new.saving": "Saving…",
  "new.failed": "The instance was not saved.",

  "request.open": "Request",
  "request.title": "Request",
  "request.text": "What do you need?",
  "request.textPlaceholder":
    "For example: clarify the requirements of CHG-002 from its stakeholders' notes, then design the change.",
  "request.textRequired": "Write what you need.",
  "request.attachments": "Attachments (optional)",
  "request.drop": "Drop files here",
  "request.chooseFiles": "Choose files",
  "request.limits": (a: { count: number; size: string }) =>
    `Up to ${a.count} attachments, each at most ${a.size}. Files are saved in the workspace (attachments in alps-harness.yaml, inbox/ by default) when the request is sent.`,
  "request.existing": "From the workspace",
  "request.chooseArtifact": "Choose an Artifact",
  "request.noArtifacts": "No Artifacts in the workspace yet",
  "request.remove": (a: { name: string }) => `Remove ${a.name}`,
  "request.uploaded": "Uploaded",
  "request.tooLarge": (a: { name: string; limit: string }) =>
    `${a.name} is larger than ${a.limit} and was not attached. Put it in the workspace and attach it from there.`,
  "request.tooMany": (a: { name: string; limit: number }) =>
    `${a.name} was not attached: a request takes at most ${a.limit} attachments.`,
  "request.folder": (a: { name: string }) =>
    `${a.name} is a folder and was not attached. Attach it from the workspace instead.`,
  "request.processes": "Processes (optional)",
  "request.processesHint":
    "Each Process you choose is in the plan; without a choice, the agent chooses.",
  "request.agent": "Agent",
  "request.mode": "How far",
  "request.run": "Run it",
  "request.plan": "Plan only",
  "request.runHint": "The agent instantiates what it plans and starts the runs.",
  "request.planHint": "The agent only instantiates what it plans; no run is started.",
  "request.send": "Send request",
  "request.sending": "Sending…",
  "request.failed": "The request was not sent.",
  "request.skipped": (a: { run: string }) =>
    `Wake run ${a.run} is still running, so this request was not started. Send it again once that wake has ended.`,

  "evaluate.title": "Evaluate",
  "evaluate.of": (a: { at: string; status: string }) => `Latest run · ${a.at} · ${a.status}`,
  "evaluate.skip": "Not judged",
  "evaluate.evidence": "Evidence (required)",
  "evaluate.evidencePlaceholder":
    "What you read or tried. That the run ended or an output exists is not evidence.",
  "evaluate.limits": "Limits (optional)",
  "evaluate.note": "Note (Markdown, optional)",
  "evaluate.save": "Record the evaluation",
  "evaluate.needOne": "Judge at least one Outcome, each with its evidence.",
  "evaluate.evidenceRequired": "Write the evidence of this judgment.",
  "evaluate.failed": "The evaluation was not recorded.",

  "filter.period": "Period",
  "period.7d": "7 days",
  "period.30d": "30 days",
  "period.90d": "90 days",
  "period.all": "All time",
  "filter.granularity": "By",
  "granularity.day": "Day",
  "granularity.week": "Week",
  "filter.process": "Process",
  "filter.agent": "Agent",
  "metric.achievement": "Outcome achievement",
  "metric.unverified": "Unverified",
  "metric.stale": "Stale evaluations",
  "metric.runSuccess": "Runs succeeded",
  "metric.duration": "Median duration",
  "metric.cost": "Usage and cost",
  "metric.judged": (a: { n: number; d: number }) => `${a.n} of ${a.d} judged`,
  "metric.awaiting": (a: { n: number }) => `${a.n} awaiting judgment`,
  "metric.staleHint":
    "Instances whose inputs or SKILL.md changed after the judgment, as they are now",
  "metric.ended": (a: { n: number; d: number }) => `${a.n} of ${a.d} ended runs`,
  "metric.p90": (a: { p90: string }) => `p90 ${a.p90}`,
  "metric.perAchieved": (a: { cost: string }) => `${a.cost} per achieved Outcome`,
  "metric.tokens": (a: { input: string; cached: string | null; output: string }) =>
    `${a.input} in${a.cached === null ? "" : ` (${a.cached} cached)`} · ${a.output} out tokens`,
  "metric.noUsage": "The agents reported no usage.",
  "unit.items": "",
  "trend.runs": "Runs and results",
  "trend.judgments": "Judgments and achievement rate",
  "trend.cost": "Cost by agent",
  "trend.duration": "Duration: median, whisker to p90",
  "trend.noData": "Nothing in this period.",
  "summary.judgments": "Judgments",
  "dashboard.error": "The statistics cannot be read.",
  "metric.now": "now",
  "chart.keys": "The arrow keys choose a period; Enter lists what it counts.",
  "findings.title": "Checks",
  "findings.none": "The checks found nothing.",
  "findings.more": (a: { n: number }) => `Show all ${a.n}`,
  "findings.less": "Show fewer",
  "findings.error": "The checks cannot be read.",
  "findingKind.description": "Description",
  "findingKind.configuration": "Configuration",
  "findingKind.unverified": "Unverified",

  "assessment.title": "Assessment",
  "assessment.empty": "No assessment yet",
  "assessment.ask": "Request an assessment",
  "assessment.interpretation": "Agent's interpretation",
  "assessment.since": (a: { runs: number; judgments: number }) =>
    `Since then ${a.runs} run${a.runs === 1 ? "" : "s"} · ${a.judgments} judgment${a.judgments === 1 ? "" : "s"}`,
  "assessment.sinceHint":
    "Process runs started and Outcome judgments made after this assessment's run started, within its scope",
  "assessment.history": "History",
  "assessment.running": "Open the assessment run",
  "assessment.error": "The assessment cannot be read.",
  "assessment.noItems": "No opportunity was recorded.",
  "assessment.pointOfView": "Point of view",
  "itemKind.description": "Description",
  "itemKind.configuration": "Configuration",
  "itemKind.operation": "Operation",
  "itemKind.unverified": "Unverified",
  "evidence.evaluation": (a: { instance: string }) => `Evaluation ${a.instance}`,
  "evidence.observation": (a: { id: string }) => `Observation ${a.id}`,
  "evidence.log": (a: { run: string; n: number }) => `Log ${a.run} #${a.n}`,
  "evidence.instance": (a: { process: string; path: string }) =>
    a.path ? `${a.process}: ${a.path}` : a.process,
  "review.open": "Review",
  "review.adopted": "Adopted",
  "review.held": "On hold",
  "review.rejected": "Rejected",
  "review.by": (a: { at: string }) => `a person · ${a.at}`,
  "review.title": "Review",
  "review.note": "Note (optional)",
  "review.save": "Record the review",
  "review.failed": "The review was not recorded.",
  "review.required": "Choose adopted, on hold, or rejected.",
  "opportunity.request": "Request from this",
  "opportunity.draft": (a: {
    statement: string;
    assessment: string;
    n: number;
    evidence: string;
  }) =>
    `${a.statement}\n\nFrom item ${a.n} of assessment ${a.assessment}.${a.evidence ? ` Evidence: ${a.evidence}.` : ""}`,
  "opportunity.description":
    "Revising the Process Description is the work of design-process-description.",
  "opportunity.configuration":
    "Revising the configuration that realizes it is the work of design-agent-work-system.",
  "assess.title": "Request an assessment",
  "assess.scope": "Scope",
  "assess.request": "Point of view (optional)",
  "assess.requestPlaceholder": "For example: why do the runs of Solution Design fail?",
  "assess.send": "Start the assessment",
  "assess.failed": "The assessment did not start.",
  "trend.rate": "achievement rate",
  "breakdown.title": "Breakdown",
  "breakdown.process": "By Process",
  "breakdown.agent": "By agent",
  "breakdown.outcome": "By Outcome",
  "breakdown.judge": "By judge",
  "col.process": "Process",
  "col.instances": "Instances",
  "col.runs": "Runs",
  "col.runSuccess": "Succeeded",
  "col.median": "Median",
  "col.achievement": "Achieved",
  "col.unverified": "Unverified",
  "col.cost": "Cost",
  "col.agent": "Agent",
  "col.perAchieved": "Cost per achieved",
  "col.runsPerInstance": "Runs per instance",
  "col.outcome": "Outcome",
  "col.counts": "Achieved · not achieved · unverified",
  "col.judge": "Judge",
  "col.judgments": "Judgments",
  "col.updated": "Updated",
  "judgeKind.user": "People",
  "judgeKind.agent": "Agents",
  "judgeKind.self": "The performer's own",
  "outcome.never": "judged, never achieved",
  "outcome.mostlyUnverified": "mostly unverified",
  "outcome.unjudged": "never judged",
  "members.instances": "Instances",
  "members.runs": "Runs",
  "members.none": "Nothing is counted here.",
  "members.since": (a: { from: string }) => `Since ${a.from}`,
  "members.allTime": "All time",
  "members.now": "As it is now, whatever the period",
  "members.bucket": (a: { from: string }) => `From ${a.from}`,

  "board.label": "Board",
  "board.stopped": "Stopped / failed",
  "board.open": (a: { process: string; id: string }) => `Open ${a.process} · ${a.id}`,
  "board.origin": (a: { run: string }) =>
    `Made by wake run ${a.run} for a request: open its record`,
  "instances.status": "Latest run",
  "instances.judgment": "Judgment",
  "instances.path": "Path contains",
  "instances.any": "Any",
  "instances.notRun": "Not run",
  "instances.judged": "Judged",
  "instances.unjudged": "Not judged",
  "instances.staleOnly": "Stale evidence",
  "instances.stale": "stale",
  "instances.none": "No instances match.",
  "instances.empty": "No instances yet.",
  "instances.count": (a: { n: number; total: number }) => `${a.n} of ${a.total}`,
  "instances.clear": "Clear the filters",
  "instances.pathPlaceholder": "Part of a path",
} satisfies Record<string, string | ((args: never) => string)>;

export type UiKey = keyof typeof en;

const ja: { [K in UiKey]: (typeof en)[K] } = {
  "agent.model": "モデル",
  "agent.effort": "エフォート",
  "agent.default": "エージェントの既定値",
  "agent.loading": "モデルを取得中…",
  "agent.noEffort": "指定なし",
  "agent.loadFailed": "モデルを取得できません。既定値での実行は可能です。",
  "agent.liveChoices": "インストール済みCLIから取得",
  "agent.refresh": "再取得",
  "app.title": "ALPS Harness",
  "brand.name": "ALPS",
  "brand.product": "Harness",
  "tab.network": "ネットワーク",
  "tab.dashboard": "アナリシス",
  "tab.instances": "ボード",
  "tabs.label": "画面",
  "count.running": (a) => `実行中 ${a.n}`,
  "count.stale": (a) => `根拠が古い ${a.n}`,
  "language.switch": "English",
  "language.label": "英語で表示する",
  "health.loading": "サーバーに接続している…",
  "health.ok": (a) => `サーバー ${a.version} · pid ${a.pid} · ポート ${a.port}`,
  "health.error": (a) => `サーバーに接続できない: ${a.message}`,
  "events.retrying": "サーバーとの接続が切れた。再接続している…",
  "events.shutdown": "ハーネスサーバーが停止した。起動し直し、印字された URL を開くこと。",
  "token.missing":
    "このページには合い言葉がない。alps-harness serve が印字した URL（…/#token=…）を開くこと。",
  "error.title": "要求は失敗した",
  retry: "もう一度試す",
  "nav.menu": "メニューを開く",
  "nav.close": "メニューを閉じる",
  "filter.allProcesses": "すべてのプロセス",
  "filter.allAgents": "すべてのエージェント",
  "theme.label": "テーマ",
  "theme.system": "システム",
  "theme.light": "ライト",
  "theme.dark": "ダーク",
  "display.transparency": "透明度を下げる",
  "events.live": "ライブ",
  "events.connecting": "接続している…",
  "events.offline": "未接続",
  "events.reconnect": "再接続",
  "count.showRunning": "最新の実行が実行中のインスタンスを一覧する",
  "count.showStale": "根拠が古いインスタンスを一覧する",
  loading: "読み込み中…",
  none: "—",

  "legend.show": "凡例",
  "legend.hide": "凡例を閉じる",
  "legend.lines": "入力・出力",
  "legend.control": "統制事項",
  "legend.running": "実行中",
  "legend.stale": "根拠が古い",
  "legend.relation": "線は関係を表し、実行の順序は表さない。",
  "legend.use": "ノードをクリックするとその周りだけを、空白をクリックすると全体を表示する。",
  "network.whole": "モデル全体",
  "network.label": "モデルのプロセスとアーティファクトの型",
  "focus.producers": "入力を作る",
  "focus.inputs": "入力・統制事項",
  "focus.process": "選んだプロセス",
  "focus.outputs": "出力",
  "focus.consumers": "出力を使う",
  "focus.typeProducers": "作るプロセス",
  "focus.type": "型",
  "focus.typeConsumers": "使うプロセス",
  "focus.given": "モデルの外から与えられる",

  "panel.close": "閉じる",
  "panel.process": "プロセス",
  "panel.type": "アーティファクトの型",
  "panel.run": "実行",
  "panel.instance": "インスタンス",
  "panel.model": "モデル",
  "panel.label": "詳細",
  "panel.open": "モデルの概要を表示",
  "panel.tabs": "区分",
  "tab.overview": "概要",
  "tab.skill": "SKILL.md",
  "overview.processes": "プロセス",
  "overview.types": "アーティファクトの型",
  "overview.workspace": "ワークスペース",
  "overview.agents": "エージェント",
  "overview.available": "使える",
  "overview.unavailable": (a) => `使えない: ${a.reason}`,
  "overview.wakes": "目覚めの記録",
  "overview.noWakes": "目覚めの記録はまだない。",
  "model.error": "モデルを読めない。",
  "model.files": "見たファイル",

  "process.outcomes": "成果",
  "process.inputs": "入力",
  "process.controls": "統制事項",
  "process.outputs": "出力",
  "process.constraints": "制約",
  "process.enablers": "実行支援要素",
  "process.noSkill": "このプロセスの SKILL.md は見つからない。",
  "process.skillMissing": (a) => `指定されたスキル ${a.location} は読める SKILL.md ではない。`,
  "process.truncated": "ファイルの先頭だけを表示している。",
  "process.instances": "インスタンス",
  "process.noInstances": "インスタンスはまだない。",
  "process.request": "このプロセスで依頼する",

  "type.kind": "種類",
  "kind.information": "情報",
  "kind.product": "製品",
  "kind.service": "サービス",
  "kind.none": "指定なし",
  "type.locations": "置き場所",
  "type.noLocation": "置き場所の設定がない（alps-harness.yaml の artifacts）。",
  "type.producedBy": "作るプロセス",
  "type.readBy": "読むプロセス",
  "type.nobody": "なし",
  "type.artifacts": "実体",
  "type.noArtifacts": "置き場所に実体はない。",
  "type.truncated": "一回の走査で読める数を超えた置き場所があり、一覧は不完全である。",
  "type.notMade": "実行の記録なし",
  "type.items": (a) => `${a.n} 項目`,

  "status.running": "実行中",
  "status.succeeded": "正常終了",
  "status.failed": "異常終了",
  "status.canceled": "中止",
  "status.interrupted": "中断",
  "run.agent": "エージェント",
  "run.instance": "インスタンス",
  "run.started": "開始",
  "run.ended": "終了",
  "run.duration": "所要時間",
  "run.usage": "使用量",
  "run.usageValue": (a) =>
    `${a.cost} · 入力 ${a.input}${a.cached === null ? "" : `（キャッシュ ${a.cached}）`} · 出力 ${a.output} トークン${a.turns === null ? "" : ` · ターン ${a.turns}`}`,
  "run.turns": "ターンはツールの往復の数に 1 を足したもの。",
  "run.report": "報告",
  "run.planReport": "報告（何をなぜ計画したか）",
  "run.noReport": "報告はない。",
  "run.request": "依頼",
  "run.noRequestText": "依頼に文面はなかった。",
  "run.processes": "指定されたプロセス",
  "run.attachments": "添付",
  "run.madeInstances": "作ったインスタンス",
  "run.noMadeInstances": "まだない。",
  "run.outputs": "出力の変化",
  "run.noOutputs": "出力の変化は見つからなかった。",
  "run.created": "作成",
  "run.modified": "更新",
  "run.sharedWith": (a) => `同時に動いた ${a.runs} の出力でもあり、どの実行が作ったかは分からない`,
  "run.inputs": "使った入力",
  "run.missing": "なかった",
  "run.log": "ログ",
  "run.following": "ログを追っている…",
  "run.earlier": "それより前のイベントは省いた。",
  "run.error": "エラー",
  "run.cancel": "実行を中止",
  "run.canceling": "中止している…",
  "run.wake": "目覚めの実行",
  "run.wakeTitle": "目覚め",
  "run.startedRuns": "起動した実行",
  "run.noStartedRuns": "起動した実行はない。",
  "run.self": "呼び出し元のセッションが実行",
  "run.assess": "アセスメントの実行",
  "run.assessTitle": "アセスメント",
  "run.scope": "範囲",

  "instance.inputs": "入力",
  "instance.outputs": "出力",
  "instance.decided": "エージェントが決める",
  "instance.notYet": "まだない",
  "instance.criteria": "基準",
  "instance.asStated": "基準は書かれていないので、成果はモデルの記述のとおりに読む。",
  "instance.checks": "確かめ方",
  "instance.notes": "注記",
  "instance.runs": "実行",
  "instance.noRuns": "まだ実行していない。",
  "instance.evaluation": "評価",
  "instance.noEvaluation": "まだ評価していない。",
  "instance.judgedRun": (a) => `${a.run} についての判断（${a.by}、${a.at}）`,
  "judge.user": "人",
  "judge.self": (a) => `${a.id}（実行者自身の判断）`,
  "instance.evidence": "根拠",
  "instance.limits": "限界",
  "instance.note": "注記",
  "instance.staleTitle": "根拠が古い",
  "instance.current": "根拠は最新",
  "instance.currentHint": "入力と SKILL.md は、判断した実行が使ったときのまま。",
  "stale.modified": (a) => `${a.path} が変わった`,
  "stale.created": (a) => `${a.path} が現れた`,
  "stale.removed": (a) => `${a.path} が消えた`,
  "stale.skill": (a) => `SKILL.md が変わった（${a.path}）`,
  "stale.definition": "プロセス記述またはこの適用の成功基準が変わった",
  "instance.agent": "エージェント",
  "instance.start": "実行する",
  "instance.starting": "開始している…",
  "instance.noAgent": "起動できるエージェントがない。",
  "instance.unavailable": (a) => `${a.label}（使えない）`,
  "instance.evaluate": "評価する",
  "instance.edit": "基準と注記を直す",
  "instance.latest": "最新の実行",
  "instance.judgments": "判断",
  "instance.createdBy": "作成した目覚め",
  "instance.earlier": "以前の評価",
  "run.startFailed": "実行は始まらなかった。",
  "run.cancelFailed": "実行は中止されなかった。",

  "judgment.achieved": "達成",
  "judgment.not-achieved": "未達成",
  "judgment.unverified": "未確認",

  "new.criteria": "この適用での各成果の意味（任意）",
  "new.statement": "基準",
  "new.checks": "確かめ方",
  "new.notes": "注記（任意）",
  "new.save": "基準と注記を保存",
  "new.cancel": "やめる",
  "new.saving": "保存している…",
  "new.failed": "インスタンスは保存されなかった。",

  "request.open": "依頼する",
  "request.title": "依頼する",
  "request.text": "依頼の内容",
  "request.textPlaceholder":
    "例：CHG-002 の関係者メモから要件を明確にし、そのうえで変更を設計してほしい。",
  "request.textRequired": "依頼の内容を書くこと。",
  "request.attachments": "添付（任意）",
  "request.drop": "ここにファイルをドロップ",
  "request.chooseFiles": "ファイルを選ぶ",
  "request.limits": (a) =>
    `添付は ${a.count} 件まで、一件 ${a.size} まで。ファイルは依頼を送るときにワークスペース（alps-harness.yaml の attachments。既定は inbox/）に保存する。`,
  "request.existing": "ワークスペースから",
  "request.chooseArtifact": "アーティファクトを選ぶ",
  "request.noArtifacts": "ワークスペースにアーティファクトはまだない",
  "request.remove": (a) => `${a.name} を外す`,
  "request.uploaded": "アップロード済み",
  "request.tooLarge": (a) =>
    `${a.name} は ${a.limit} より大きいので添付しなかった。ワークスペースに置き、そこから添付すること。`,
  "request.tooMany": (a) =>
    `${a.name} は添付しなかった。一回の依頼で添付できるのは ${a.limit} 件までである。`,
  "request.folder": (a) =>
    `${a.name} はフォルダなので添付しなかった。ワークスペースから添付すること。`,
  "request.processes": "プロセス（任意）",
  "request.processesHint": "選んだプロセスは必ず計画に含まれる。選ばなければエージェントが選ぶ。",
  "request.agent": "エージェント",
  "request.mode": "どこまで進めるか",
  "request.run": "実行まで進める",
  "request.plan": "計画だけ",
  "request.runHint": "エージェントは計画したものをインスタンス化し、実行を開始する。",
  "request.planHint": "エージェントは計画したものをインスタンス化するだけで、実行は開始しない。",
  "request.send": "依頼を送る",
  "request.sending": "送っている…",
  "request.failed": "依頼は送られなかった。",
  "request.skipped": (a) =>
    `目覚めの実行 ${a.run} がまだ動いているので、この依頼は始まらなかった。その目覚めが終わってから送り直すこと。`,

  "evaluate.title": "評価",
  "evaluate.of": (a) => `最新の実行 · ${a.at} · ${a.status}`,
  "evaluate.skip": "判断しない",
  "evaluate.evidence": "根拠（必須）",
  "evaluate.evidencePlaceholder":
    "読んだものや試したこと。実行が終わったことや出力があることは根拠にならない。",
  "evaluate.limits": "限界（任意）",
  "evaluate.note": "注記（Markdown、任意）",
  "evaluate.save": "評価を記録",
  "evaluate.needOne": "少なくとも一つの成果を、根拠を添えて判断すること。",
  "evaluate.evidenceRequired": "この判断の根拠を書くこと。",
  "evaluate.failed": "評価は記録されなかった。",

  "filter.period": "期間",
  "period.7d": "7 日",
  "period.30d": "30 日",
  "period.90d": "90 日",
  "period.all": "全期間",
  "filter.granularity": "粒度",
  "granularity.day": "日",
  "granularity.week": "週",
  "filter.process": "プロセス",
  "filter.agent": "エージェント",
  "metric.achievement": "成果の達成率",
  "metric.unverified": "未確認率",
  "metric.stale": "根拠が古い評価",
  "metric.runSuccess": "実行の正常終了率",
  "metric.duration": "所要時間の中央値",
  "metric.cost": "使用量と費用",
  "metric.judged": (a) => `判断 ${a.d} 件中 ${a.n} 件`,
  "metric.awaiting": (a) => `判断待ち ${a.n} 件`,
  "metric.staleHint": "判断の後に入力か SKILL.md が変わったインスタンス（今の状態）",
  "metric.ended": (a) => `終わった実行 ${a.d} 件中 ${a.n} 件`,
  "metric.p90": (a) => `p90 ${a.p90}`,
  "metric.perAchieved": (a) => `達成 1 件あたり ${a.cost}`,
  "metric.tokens": (a) =>
    `トークン 入力 ${a.input}${a.cached === null ? "" : `（キャッシュ ${a.cached}）`} · 出力 ${a.output}`,
  "metric.noUsage": "エージェントが使用量を報告していない。",
  "unit.items": "件",
  "trend.runs": "実行数と結果",
  "trend.judgments": "判断と達成率",
  "trend.cost": "エージェント別の費用",
  "trend.duration": "所要時間：中央値と p90 までの髭",
  "trend.noData": "この期間には何もない。",
  "summary.judgments": "判断",
  "dashboard.error": "統計を読めない。",
  "metric.now": "現在",
  "chart.keys": "矢印キーで期間を選び、Enter でその期間に数えたものを一覧する。",
  "findings.title": "検査",
  "findings.none": "検査で見つかったことはない。",
  "findings.more": (a) => `${a.n} 件すべて表示`,
  "findings.less": "表示を減らす",
  "findings.error": "検査を読めない。",
  "findingKind.description": "記述",
  "findingKind.configuration": "構成",
  "findingKind.unverified": "未確認",

  "assessment.title": "アセスメント",
  "assessment.empty": "まだアセスメントはない",
  "assessment.ask": "アセスメントを依頼",
  "assessment.interpretation": "エージェントの解釈",
  "assessment.since": (a) => `その後 実行 ${a.runs}・判断 ${a.judgments}`,
  "assessment.sinceHint":
    "このアセスメントの実行の開始後に、その範囲で始まったプロセスの実行と、記録された成果の判断",
  "assessment.history": "履歴",
  "assessment.running": "アセスメントの実行を開く",
  "assessment.error": "アセスメントを読めない。",
  "assessment.noItems": "改善の機会は記録されていない。",
  "assessment.pointOfView": "観点",
  "itemKind.description": "記述",
  "itemKind.configuration": "構成",
  "itemKind.operation": "運用",
  "itemKind.unverified": "未確認",
  "evidence.evaluation": (a) => `評価 ${a.instance}`,
  "evidence.observation": (a) => `観測 ${a.id}`,
  "evidence.log": (a) => `ログ ${a.run} #${a.n}`,
  "evidence.instance": (a) => (a.path ? `${a.process}: ${a.path}` : a.process),
  "review.open": "確認する",
  "review.adopted": "採用",
  "review.held": "保留",
  "review.rejected": "却下",
  "review.by": (a) => `人 · ${a.at}`,
  "review.title": "確認",
  "review.note": "注記（任意）",
  "review.save": "確認を記録",
  "review.failed": "確認は記録されなかった。",
  "review.required": "採用・保留・却下のいずれかを選ぶこと。",
  "opportunity.request": "この機会から依頼する",
  "opportunity.draft": (a) =>
    `${a.statement}\n\nアセスメント ${a.assessment} の項目 ${a.n} から。${a.evidence ? `根拠: ${a.evidence}。` : ""}`,
  "opportunity.description": "プロセスの記述の見直しは design-process-description の仕事。",
  "opportunity.configuration": "それを実現する構成の見直しは design-agent-work-system の仕事。",
  "assess.title": "アセスメントを依頼",
  "assess.scope": "範囲",
  "assess.request": "観点（任意）",
  "assess.requestPlaceholder": "例：Solution Design の実行が失敗するのはなぜか",
  "assess.send": "アセスメントを始める",
  "assess.failed": "アセスメントは始まらなかった。",
  "trend.rate": "達成率",
  "breakdown.title": "内訳",
  "breakdown.process": "プロセス別",
  "breakdown.agent": "エージェント別",
  "breakdown.outcome": "成果別",
  "breakdown.judge": "判断者別",
  "col.process": "プロセス",
  "col.instances": "インスタンス",
  "col.runs": "実行",
  "col.runSuccess": "正常終了率",
  "col.median": "中央値",
  "col.achievement": "達成率",
  "col.unverified": "未確認率",
  "col.cost": "費用",
  "col.agent": "エージェント",
  "col.perAchieved": "達成あたりの費用",
  "col.runsPerInstance": "インスタンスあたりの実行",
  "col.outcome": "成果",
  "col.counts": "達成・未達成・未確認",
  "col.judge": "判断者",
  "col.judgments": "判断",
  "col.updated": "更新",
  "judgeKind.user": "人",
  "judgeKind.agent": "エージェント",
  "judgeKind.self": "実行者自身",
  "outcome.never": "判断されたが一度も達成されていない",
  "outcome.mostlyUnverified": "未確認が過半",
  "outcome.unjudged": "判断されていない",
  "members.instances": "インスタンス",
  "members.runs": "実行",
  "members.none": "数えたものはない。",
  "members.since": (a) => `${a.from} 以降`,
  "members.allTime": "全期間",
  "members.now": "期間に関わらず今の状態",
  "members.bucket": (a) => `${a.from} から`,

  "board.label": "ボード",
  "board.stopped": "停止・異常終了",
  "board.open": (a) => `${a.process} · ${a.id} の詳細を開く`,
  "board.origin": (a) => `依頼の目覚め ${a.run} で作成。その記録を開く`,
  "instances.status": "最新の実行",
  "instances.judgment": "判断",
  "instances.path": "パスの一部",
  "instances.any": "すべて",
  "instances.notRun": "未実行",
  "instances.judged": "判断あり",
  "instances.unjudged": "判断なし",
  "instances.staleOnly": "根拠が古い",
  "instances.stale": "古い",
  "instances.none": "該当するインスタンスはない。",
  "instances.empty": "インスタンスはまだない。",
  "instances.count": (a) => `${a.total} 件中 ${a.n} 件`,
  "instances.clear": "絞り込みを解除",
  "instances.pathPlaceholder": "パスの一部",
};

const CATALOG: Record<Language, { [K in UiKey]: (typeof en)[K] }> = { en, ja };

/** The arguments of a text: none for a plain string. */
export type UiArgs<K extends UiKey> = (typeof en)[K] extends (args: infer A) => string ? [A] : [];

/** A text of the WebUI in a language. */
export function text<K extends UiKey>(language: Language, key: K, ...args: UiArgs<K>): string {
  const entry = CATALOG[language][key] as string | ((args: unknown) => string);
  return typeof entry === "string" ? entry : entry(args[0]);
}

export type Translate = <K extends UiKey>(key: K, ...args: UiArgs<K>) => string;

export const translator =
  (language: Language): Translate =>
  (key, ...args) =>
    text(language, key, ...args);

/** The browser's language, if the WebUI speaks it; English otherwise. */
export function browserLanguage(languages: readonly string[]): Language {
  for (const tag of languages) {
    const primary = tag.toLowerCase().split("-")[0];
    if (primary === "ja") return "ja";
    if (primary === "en") return "en";
  }
  return "en";
}
